### ISSUE TITLE
Add HotKeys in file tree

### ISSUE THREAD

**Issue by qingyu910** [martin-holy/PictureManager#21]
Add Delete or Open In Explorer hotkeys will help manage files and folders. It would also be useful to add a setting that must be confirm when deleting file.

**Comment by martin-holy** [comment]
Hi, I didn't know that someone is actually using my app 😁. Otherwise I'd make release more often.
I just started a  huge rewrite of TreeView today, so it will take a while before I do anything else.
There is delete confirmation for folders and files in the current version which is not released yet, so I will close this for now and you can have a look what you would  want to add when the new version is released.
